services:
  app:
    build: .
    image: service
    command: gunicorn --workers=3 --bind=:8000 --env DJANGO_SETTINGS_MODULE=configs.settings configs.wsgi
    volumes:
      - /:/web/media/
      # - /cloud/service-documents/:/web/media/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: always